/* Generated by tools/build_standalone.py; only this game directory is cached. */
const CACHE = 'sa-hoops-3c3252023c02dd7a';
const FILES = ["index.html", "styles.css", "locales.js", "game-core.js", "renderer.js", "app.js", "manifest.webmanifest", "icon.svg", "guide.html"];
self.addEventListener('install', event => {
  event.waitUntil(caches.open(CACHE).then(cache => cache.addAll(FILES)).then(() => self.skipWaiting()));
});
self.addEventListener('activate', event => {
  event.waitUntil(caches.keys().then(keys => Promise.all(keys.filter(k => k.startsWith('sa-hoops-') && k !== CACHE).map(k => caches.delete(k)))).then(() => self.clients.claim()));
});
self.addEventListener('fetch', event => {
  const url = new URL(event.request.url);
  if (event.request.method !== 'GET' || url.origin !== self.location.origin || !url.href.startsWith(self.registration.scope)) return;
  event.respondWith(caches.open(CACHE).then(async cache => {
    const hit = await cache.match(event.request); if (hit) return hit;
    try { const response = await fetch(event.request); if (response.ok) await cache.put(event.request, response.clone()); return response; }
    catch(error) { if (event.request.mode === 'navigate') return (await cache.match(new URL('index.html', self.registration.scope).href)) || Response.error(); throw error; }
  }));
});
